"""
Wraps a trained Stable-Baselines3 model as a Kaggle-compatible agent function,
and can export a self-contained submission.py with embedded weights.
"""

from __future__ import annotations

import base64
import math
import os
import tempfile
from pathlib import Path
from typing import Callable

import numpy as np


class RLAgent:
    """
    Loads a saved SB3 model and exposes a Kaggle-compatible __call__ interface.

    Usage
    -----
    agent = RLAgent("outputs/checkpoints/best_model.zip")
    env.run([agent, "random"])
    """

    def __init__(self, model_path: str | Path, device: str = "cpu"):
        from stable_baselines3 import PPO
        from envs.orbit_wars_env import OrbitWarsEnv, OBS_DIM

        self._model = PPO.load(str(model_path), device=device)
        # Use env only for encode/decode helpers — no game state
        self._env = OrbitWarsEnv.__new__(OrbitWarsEnv)
        self._obs_dim = OBS_DIM

    def __call__(self, obs, config=None) -> list:
        from envs.orbit_wars_env import _player
        player = _player(obs)
        obs_vec = self._env._encode(obs, player)
        action, _ = self._model.predict(obs_vec[np.newaxis], deterministic=True)
        own_s, tgt_s, frac = int(action[0][0]), int(action[0][1]), int(action[0][2])
        return self._env._decode_action(obs, own_s, tgt_s, frac)


def export_submission(
    model_path: str | Path | None,
    output_path: str | Path = "outputs/submissions/submission.py",
    mode: str = "rl",
) -> Path:
    """
    Generate a single self-contained submission.py for Kaggle.

    Parameters
    ----------
    model_path : path to .zip weights, or None when mode is a rule-based agent
    output_path : where to write the file
    mode : 'competitive' | 'hybrid' | 'rl'

    Returns
    -------
    Path to the written file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if mode == "competitive":
        code = _competitive_submission_code()
    elif mode == "hybrid":
        code = _hybrid_submission_code()
    elif mode == "rl":
        if model_path is None:
            raise ValueError("model_path required for mode='rl'")
        weights_b64 = _encode_weights(Path(model_path))
        code = _rl_submission_code(weights_b64)
    else:
        raise ValueError(f"mode must be 'competitive', 'hybrid', or 'rl', got {mode!r}")

    output_path.write_text(code)
    size_kb = output_path.stat().st_size // 1024
    print(f"Wrote {output_path}  ({size_kb} KB)")
    return output_path


# ── internal helpers ───────────────────────────────────────────────────────

def _encode_weights(path: Path) -> str:
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")


def _hybrid_submission_code() -> str:
    """Read agents/hybrid.py and wrap it as a submission."""
    here = Path(__file__).parent
    source = (here / "hybrid.py").read_text()
    return source


def _competitive_submission_code() -> str:
    """Read agents/competitive.py and wrap it as a submission."""
    here = Path(__file__).parent
    source = (here / "competitive.py").read_text()
    return source


def _rl_submission_code(weights_b64: str) -> str:
    from envs.orbit_wars_env import OBS_DIM, MAX_PLANETS, MAX_FLEETS, SHIP_FRACTIONS
    fracs_repr = repr(SHIP_FRACTIONS)

    return f'''\
"""
Orbit Wars submission — PPO agent with embedded weights.
Auto-generated by agents/rl_agent.py — do not edit by hand.
"""
import base64, math, os, tempfile
import numpy as np

_WEIGHTS_B64 = (
    "{weights_b64}"
)

_MAX_P = {MAX_PLANETS}
_MAX_F = {MAX_FLEETS}
_OBS_DIM = {OBS_DIM}
_FRACS = {fracs_repr}

_MODEL = None

def _load():
    global _MODEL
    if _MODEL is not None:
        return _MODEL
    from stable_baselines3 import PPO
    with tempfile.NamedTemporaryFile(suffix=".zip", delete=False) as f:
        f.write(base64.b64decode(_WEIGHTS_B64))
        tmp = f.name
    _MODEL = PPO.load(tmp, device="cpu")
    os.unlink(tmp)
    return _MODEL

def _encode(obs):
    player = obs.player if hasattr(obs, "player") else obs.get("player", 0)
    raw_p  = obs.planets if hasattr(obs, "planets") else obs.get("planets", [])
    raw_f  = obs.fleets  if hasattr(obs, "fleets")  else obs.get("fleets",  [])
    step   = obs.step if hasattr(obs, "step") else obs.get("step", 0)
    av     = obs.angular_velocity if hasattr(obs, "angular_velocity") else obs.get("angular_velocity", 0.0)
    comets = obs.comet_planet_ids if hasattr(obs, "comet_planet_ids") else obs.get("comet_planet_ids", [])

    v = np.zeros(_OBS_DIM, np.float32)
    v[0] = step / 500.0
    v[1] = av / 0.05
    v[2] = len(comets) / 4.0

    base = 3
    for i, p in enumerate(raw_p[:_MAX_P]):
        b = base + i * 7
        v[b+0] = 1.0 if p[1] == player else 0.0
        v[b+1] = 1.0 if p[1] >= 0 and p[1] != player else 0.0
        v[b+2] = 1.0 if p[1] == -1 else 0.0
        v[b+3] = p[2] / 100.0
        v[b+4] = p[3] / 100.0
        v[b+5] = math.log1p(p[5]) / 10.0
        v[b+6] = p[6] / 5.0

    base = 3 + _MAX_P * 7
    for i, f in enumerate(raw_f[:_MAX_F]):
        b = base + i * 5
        v[b+0] = 1.0 if f[1] == player else 0.0
        v[b+1] = 1.0 if f[1] != player else 0.0
        v[b+2] = f[2] / 100.0
        v[b+3] = f[3] / 100.0
        v[b+4] = math.log1p(f[6]) / 10.0
    return v

def agent(obs, config=None):
    model = _load()
    player = obs.player if hasattr(obs, "player") else obs.get("player", 0)
    raw_p  = obs.planets if hasattr(obs, "planets") else obs.get("planets", [])

    obs_vec = _encode(obs)
    action, _ = model.predict(obs_vec[np.newaxis], deterministic=True)
    own_s, tgt_s, frac_bin = int(action[0][0]), int(action[0][1]), int(action[0][2])

    planets = [(p[0], p[1], p[2], p[3], p[5]) for p in raw_p]  # id, owner, x, y, ships
    my_p = sorted([p for p in planets if p[1] == player], key=lambda p: p[0])

    if own_s >= len(my_p) or tgt_s >= len(planets):
        return []
    src = my_p[own_s]
    tgt = planets[tgt_s]
    if tgt[0] == src[0]:
        return []

    ships = max(1, int(src[4] * _FRACS[frac_bin]))
    if ships >= src[4]:
        ships = max(1, src[4] - 1)

    return [[src[0], math.atan2(tgt[3] - src[3], tgt[2] - src[2]), ships]]
'''
